### ISSUE TITLE
[BUG] src/components/storage.tsx 45行代码有问题

### ISSUE THREAD

**Issue by xpfoxs** [liuw5367/chatgpt-web#11]
chatConfigAtom.set({
    accessCode: localStorage.getItem('accessCode') || undefined,
    openAIKey: localStorage.getItem('openAIKey') || undefined,
    openAIHost: localStorage.getItem('openAIHost') || undefined,
    openAIModel: localStorage.getItem('openAIModel') || undefined,
    temperature: localStorage.getItem('temperature') ?? '0.6',
    top_p: localStorage.getItem('top_p') ?? '1',
    searchSuggestions: localStorage.getItem('searchSuggestions') ?? '1',
    enterSend: localStorage.getItem('**searchSuggestions**') ?? '',

    unisoundAppKey: localStorage.getItem('unisoundAppKey') || undefined,
    unisoundSecret: localStorage.getItem('unisoundSecret') || undefined,
  });

    enterSend: localStorage.getItem('searchSuggestions')
     这里应该是
    enterSend: localStorage.getItem('**enterSend**')

**Comment by liuw5367** [comment]
多谢，明天我改一下 🤦‍♂️ 最近太忙了，好久没更新
